service: candidates-app

provider:
  name: aws
  runtime: nodejs4.3
  stage: prod

functions:
  hello: 
    handler: handler.hello
    events: 
      - http: 
          path: hello
          method: get
          cors: true
